{{- if .Values.harborRobot }}
apiVersion: v1
kind: Secret
metadata:
  name: harbor-robot
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tatara-argo-workflows.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "harbor.robotUsername required (chart values)" .Values.harbor.robotUsername | quote }}
  password: {{ required "harborRobot.password required (from sops values)" .Values.harborRobot.password | quote }}
{{- end }}
